### ISSUE TITLE
ts-for-gir and gi.ts

### ISSUE THREAD

**Issue by marcinjahn** [gjsify/ts-for-gir#120]
I'd like to understand what is the difference between this project and https://gitlab.gnome.org/ewlsh/gi.ts/-/tree/master/?
Are these two separate projects that tackle the same problem?

**Comment by JumpLink** [comment]
@marcinjahn yes it is so. When I started this project, gi.ts was not working, so I couldn't test it, otherwise I would have contributed there. Instead I contributed to this project which was originally initiated by @sammydre and I took over with time. I think now we can try different things in both projects and in the end maybe implement the best practices and maybe merge the projects again.

Currently this project has a few features that I need for my projects, so I don't want to give it up.

**Comment by ewlsh** [comment]
Hi :wave: I started gi.ts in 2019 when _from what I gathered at the time_ this project had gone inactive. At that point the type definitions produced by this project did not accurately reflect GJS and weren't usable in my projects (e.g. typechecking gnome-shell and GJS itself) and I wanted to try rebuilding aspects of the type generation from the ground-up. Since then, @JumpLink has done a great work with this project while I have also made incremental updates to gi.ts. As @JumpLink points out, each project has its strengths and weaknesses when it comes to fully supporting GJS' APIs and features.

At this point, I hope we can find a way to unify the projects so the community benefits and we can work together on improvements going forward. I'll ping you on Matrix @JumpLink :smiley_cat:

**Comment by JumpLink** [comment]
Work in progress on https://github.com/gjsify/ts-for-gir/pull/144
