### ISSUE TITLE
Missing runAsync overrides

### ISSUE THREAD

**Issue by nahuelwexd** [gjsify/ts-for-gir#130]
IIRC since GNOME 44, GJS incorporates a new override for `Gio.Application` and `GLib.MainLoop`: `runAsync`.

`runAsync` behaves similar to `run`, with the exception that it returns a `Promise<number>` instead of a `number`. It serves to avoid situations like promises never ending if you didn't run the main loop or the application inside a callback.

- https://gitlab.gnome.org/GNOME/gjs/-/blob/eb191f2dd9a54632ce5ba4e015a2817b7bf7f933/doc/Overrides.md#gioapplicationrunasync
- https://gitlab.gnome.org/GNOME/gjs/-/blob/eb191f2dd9a54632ce5ba4e015a2817b7bf7f933/doc/Overrides.md#glibmainlooprunasync

**Comment by JumpLink** [comment]
Hey @nahuelwexd,

Thanks for bringing up the new runAsync override in GJS as of GNOME 44. It sounds like an important update that our tool should definitely reflect, especially since it changes how Gio.Application and GLib.MainLoop work by returning a Promise<number> instead of just a number.

I'll tag this issue appropriately to keep track of it. Given the significance of this update, I’ll aim to address it when I dive into updating the tool for the latest GJS features.

Just like with the other issue, it would be super helpful if you could provide a small code snippet showing how runAsync is intended to be used or where the current implementation falls short. This will give me a clearer idea of what needs to be tweaked or added in our tool.

I'll get to this as soon as I can carve out some time. Your contributions and patience are greatly appreciated!

Catch you later with updates. Thanks for sticking with us!

**Comment by YarnSphere** [comment]
> Just like with the other issue, it would be super helpful if you could provide a small code snippet showing how runAsync is intended to be used or where the current implementation falls short. This will give me a clearer idea of what needs to be tweaked or added in our tool.

I believe that this should all type check:
```ts
import Adw from "gi://Adw";
import GLib from "gi://GLib";
import Gio from "gi://Gio";
import Gtk from "gi://Gtk?version=4.0";

const mainLoop = new GLib.MainLoop(null, false);
mainLoop.runAsync().then(() => {
  console.log("Exited");
});

const gioApp = new Gio.Application();
gioApp.runAsync(ARGV).then((exitStatus: number) => {
  console.log(`Exited with status: ${exitStatus}`);
});

const gtkApp = new Gtk.Application();
gtkApp.runAsync(ARGV).then((exitStatus: number) => {
  console.log(`Exited with status: ${exitStatus}`);
});

const adwApp = new Adw.Application();
adwApp.runAsync(ARGV).then((exitStatus: number) => {
  console.log(`Exited with status: ${exitStatus}`);
});
```
