### ISSUE TITLE
Missing some async/finish functions

### ISSUE THREAD

**Issue by vixalien** [gjsify/ts-for-gir#200]
Hello.

When using types generated by ts-for-gir 4.x, I found that some functions are not being detected as async/finish functions.

Functions with a signature resembling `function_name_async` and then `function_name_finish` seem to be generated correctly, but functions with a signature resembling `function_name` and then `function_name_finish` don't seem to be generated correctly.

Some examples include:

- `Gtk.FileDialog.open_multiple`
- `Gtk.ColorDialog.choose_rgba`
- `Xdp.Camera.access_portal`
- `Xdp.Portal.pick_color`
- `Gtk.FileDialog.open`
- `Xdp.Portal.session_monitor_start`
- most other `Xdp.Portal.*` functions

A possible way to detect these would be to check if a function's last parameter is a `Gio.AsyncReadyCallback`, and then detecting if there's a similar function with `_finish` suffix AND which takes in a `Gio.AsyncResult` as only parameter.

**Comment by badcel** [comment]
Another idea would be to add [annotations upstream](https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/main/docs/gir-1.2.rnc#L529) so other bindings can benefit and do not need to add heuristics, too.

**Comment by vixalien** [comment]
Yeah. We would likely need to create an initiative to add these annotations. Would be better as a coordinated effort imo.

**Comment by badcel** [comment]
My philosophy is to do it on a case by case basis. I started adding some `ref-func` annotations [upstream](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4161#note_2192105) because my project would benefit from it.

If some async function annotations are missing the specifically requested ones would be added by myself. Fixing all the annotations in a big effort would probably add a lot of burden to the maintainers of the upstream libraries and on the own binding project, too.

I just wanted to mention the annotations as from my point of view they are technically the better solution to the problem of missing async functions.

At least for my C# bindings I decided to not add more heuristics but to fix upstream instead.

**Comment by JumpLink** [comment]
@vixalien do you mean the promisified version of the types? Then that should be fixed with the last release 🎉

**Comment by vixalien** [comment]
Yeah that's what I was talking about. I'll check the latest types. Thanks!!!

**Comment by JumpLink** [comment]
Fixed with #210 and https://github.com/gjsify/ts-for-gir/commit/d3644fd436e5fdf39239c895b1b936a470eb6eca
