### ISSUE TITLE
Missing Types for GNOME Shell imports

### ISSUE THREAD

**Issue by pcbowers** [gjsify/ts-for-gir#99]
This is more a feature re quest than a bug: currently, most GNOME API's and GJS built-in  modules have types through this package, but (unless I'm missing something), GNOME Shell imports are not typed (i.e. `imports.misc` and `imports.ui`). I would love to see this implemented! This has made working with GJS infinitely better.

**Comment by JumpLink** [comment]
Hi @pcbowers,
I have now added [initial support](https://github.com/sammydre/ts-for-gir/commit/4b8b03316e60a5a0ab61dc2273120b94ef084f79) for GNOME Shell Extensions, which should make it easier for others to contribute more types to this project. Since I am currently not working on any extensions, I don't have this in focus. Because `imports.misc` and `imports.ui` [are written in JavaScript](https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/main/js/), these types cannot be automatically generated and must instead be mostly written by hand. I have done this as an example for [imports.misc.extensionUtils](https://github.com/sammydre/ts-for-gir/blob/master/packages/cli/templates/Gjs/misc/extensionUtils.d.ts) and also added an [example](https://github.com/sammydre/ts-for-gir/tree/master/examples/Gjs/gnome-shell-hello-world).

If you are creating the corresponding types for your project anyway, we would be very happy if you could send them back to us. For this, they would just have to be inserted [here](https://github.com/sammydre/ts-for-gir/blob/master/packages/cli/templates/Gjs/GnomeShell.d.ts).

**Comment by swsnr** [comment]
I just noticed this as well, and it seems that these types are included unconditionally, see https://github.com/sammydre/ts-for-gir/issues/101#issuecomment-1385116676

Would you mind to add an option to turn the shell types off, to have correct types in a plain Gjs environment?

**Comment by JumpLink** [comment]
@swsnr done

**Comment by JumpLink** [comment]
To enable GNOME Shell Types you need to pass the new option `--gnomeShellTypes`, now. 

You can reuse the config file from the [GNOME Shell Example](https://github.com/sammydre/ts-for-gir/tree/master/examples/Gjs/gnome-shell-hello-world), in which the `girDirectories` option must also be modified to include all types needed for GNOME Shell extensions:

```js
module.exports = {
    environments: ["gjs"],
    modules: ["St-1.0"],
    girDirectories: [
        // General gir files
        '/usr/share/gir-1.0',

        // GNOME Shell gir file (package: gnome-shell-common / gnome-shell)
        '/usr/share/gnome-shell',
        '/usr/share/gnome-shell/gir-1.0',

        // GNOME Shell gir file dependencies on Fedora Workstation 36 (package: mutter)
        '/usr/lib64/mutter-10',

        // GNOME Shell gir file dependencies on Fedora Workstation 37 (package: mutter)
        '/usr/lib64/mutter-11',

        //  GNOME Shell gir file dependencies on Ubuntu 22.04 (package: libmutter-10-dev)
        '/usr/lib/x86_64-linux-gnu/mutter-10',

        //  GNOME Shell gir file dependencies on Ubuntu 22.10 (package: libmutter-11-dev)
        '/usr/lib/x86_64-linux-gnu/mutter-11',
    ],
    pretty: true,
    moduleType: "commonjs",
    gnomeShellTypes: true,
}
```

**Comment by gilbertorconde** [comment]
Dont know if this is the best place to comment about this but by using that example folder (the one on https://github.com/gjsify/ts-for-gir/tree/main/examples/Gjs/gnome-shell-hello-world) the imports don't really work. I had to add:
```
"paths": {
    "@imports/*": ["../@types/*"]
 }
  ```
To the compiler options of the tsconfig.json

**Comment by sansmoraxz** [comment]
Not sure if I did it right, but `imports.misc.extensionUtils.getSettings()` function wasn't generated in the `ExtensionUtils.d.ts`.

Here's the command I used for reference:
`yarn ts-for-gir generate Gtk-3.0 --generateAlias --gnomeShellTypes`

**Comment by JumpLink** [comment]
@gilbertorconde @sansmoraxz @swsnr @pcbowers I have moved the TypeScript types for the GNOME Shell to this repository: https://github.com/gjsify/gnome-shell.

The types are written by hand, so if you find errors that can be corrected quickly by hand, I would be happy about a PR/MR, but a new issue is also welcome.
